<a href="https://colab.research.google.com/github/2811619/Independent_Study_Research/blob/main/CIS_698.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import datetime as dt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
dataframe = pd.concat(pd.read_excel(r"/content/drive/MyDrive/Raw data_Content(2010-2020).xlsx",
                       sheet_name=['2010_ALL', '2011_ALL', '2012_ALL', '2013_ALL', '2014_ALL', '2015_ALL', '2016_ALL', '2017_ALL', '2018_ALL', '2019_ALL', '2020_ALL']))

In [4]:
dataframe

                                                  Form & File  \
2010_ALL 0                         10-K (Annual report) EX-13
         1    20-F (Annual report - foreign issuer) EX-15.(B)
2011_ALL 0                         10-K (Annual report) EX-13
         1                               10-K (Annual report)
         2                               10-K (Annual report)
...                                                       ...
2020_ALL 325            20-F (Annual report - foreign issuer)
         326            20-F (Annual report - foreign issuer)
         327               40-F (Registration statement) EX-1
         328             40-F (Registration statement) EX-1.1
         329            40-F (Registration statement) EX-99.1

             Filed\n(YYYY-MM-DD) Reporting for\n(YYYY-MM-DD)  \
2010_ALL 0            2010-03-01                  2010-01-01
         1            2010-02-22                  2009-12-31
2011_ALL 0            2011-03-01                  2010-12-31
         1            2011-03-01                  2010-12-31
         2            2011-05-20                  2011-03-31
...                          ...                         ...
2020_ALL 325          2020-01-29                  2019-12-31
         326          2020-03-26                  2019-12-31
         327          2020-03-27                  2019-12-31
         328          2020-03-11                  2019-12-31
         329          2020-03-30                  2019-12-31

                                  Filing entity/person   SIC  \
2010_ALL 0                                 TELLABS INC  3661
         1    KONINKLIJKE PHILIPS ELECTRONICS NV (PHG)  3600
2011_ALL 0                                 TELLABS INC  3661
         1                                 TELLABS INC  3661
         2                              AVX Corp (AVX)  3670
...                                                ...   ...
2020_ALL 325                         NOVARTIS AG (NVS)  2834
         326     British American Tobacco p.l.c. (BTI)  2111
         327             MAGNA INTERNATIONAL INC (MGA)  3714
         328                SIERRA WIRELESS INC (SWIR)  3663
         329              ELDORADO GOLD CORP /FI (EGO)  1040

             CIK\n(full 10 digit)                   Located  \
2010_ALL 0                 317771            Naperville, IL
         1                 313216             Amsterdam, P7
2011_ALL 0                 317771            Naperville, IL
         1                 317771            Naperville, IL
         2                 859163          Fountain Inn, SC
...                           ...                       ...
2020_ALL 325              1114448                 Basel, V8
         326              1303523                London, X0
         327               749098  Aurora, Ontario, Can, A6
         328              1111863              Richmond, A1
         329               918608             Vancouver, A1

                          Incorporated  \
2010_ALL 0                    Delaware
         1                 Netherlands
2011_ALL 0                    Delaware
         1                    Delaware
         2                    Delaware
...                                ...
2020_ALL 325               Switzerland
         326                       NaN
         327                       NaN
         328  British Columbia, Canada
         329  British Columbia, Canada

                                            Conflict mineral(s) *adverse*  \
2010_ALL 0    Supply Chain\n\nExpect excellence\n\nthroughou...  00:00:00
         1    \t \t‘Conflict’ minerals: issues further down ...  00:00:00
2011_ALL 0    Work with supply chain to responsibly manage m...         0
         1    Conflict Minerals — Minerals such as gold, tin...         0
         2    Changes in regulatory and environmental compli...         1
...                                                         ...       ...
2020_ALL 325  Our reliance on outsourcing key business funct...         1
         326  Supplier Code of Conduct. Standards required o...         0
         327  Conflict Minerals Reporting. Consistent with t...         0
         328  Additional Information Concerning Our Business...         0
         329  We are also subject to changing rules and regu...         0

              *expense*,*cost*  *reputation*  *difficult*  *support*  \
2010_ALL 0                   0             0            0          0
         1                   0             0            0          0
2011_ALL 0                   0             0            0          0
         1                   0             0            0          0
         2                   1             0            1          0
...                        ...           ...          ...        ...
2020_ALL 325                 0             1            0          0
         326                 0             0            0          0
         327                 0             1            0          1
         328                 1             1            1          0
         329                 1             0            1          0

                         *commit*  *effort*  *compliance*, *comply*
2010_ALL 0    1900-01-01 00:00:00  00:00:00                     0.0
         1               00:00:00  00:00:00                     0.0
2011_ALL 0                      1         0                     1.0
         1                      0         0                     0.0
         2                      0         0                     1.0
...                           ...       ...                     ...
2020_ALL 325                    0       NaN                     NaN
         326                    0       NaN                     NaN
         327                    0       NaN                     NaN
         328                    1       NaN                     NaN
         329                    0       NaN                     NaN

[3729 rows x 17 columns]

In [5]:
#Checking the null values
count = dataframe.isnull().sum()
print(count)

Form & File                      0
Filed\n(YYYY-MM-DD)              0
Reporting for\n(YYYY-MM-DD)      1
Filing entity/person             0
SIC                              0
CIK\n(full 10 digit)             0
Located                         14
Incorporated                   491
Conflict mineral(s)              4
*adverse*                        0
*expense*,*cost*                 0
*reputation*                     0
*difficult*                      0
*support*                        0
*commit*                         0
*effort*                       283
*compliance*, *comply*         283
dtype: int64

In [6]:
dataframe = dataframe.dropna()
dataframe.isnull().sum()

Form & File                    0
Filed\n(YYYY-MM-DD)            0
Reporting for\n(YYYY-MM-DD)    0
Filing entity/person           0
SIC                            0
CIK\n(full 10 digit)           0
Located                        0
Incorporated                   0
Conflict mineral(s)            0
*adverse*                      0
*expense*,*cost*               0
*reputation*                   0
*difficult*                    0
*support*                      0
*commit*                       0
*effort*                       0
*compliance*, *comply*         0
dtype: int64

In [7]:
dataframe

                                                 Form & File  \
2010_ALL 0                        10-K (Annual report) EX-13
         1   20-F (Annual report - foreign issuer) EX-15.(B)
2011_ALL 0                        10-K (Annual report) EX-13
         1                              10-K (Annual report)
         2                              10-K (Annual report)
...                                                      ...
2020_ALL 41                             10-K (Annual report)
         42                             10-K (Annual report)
         44                             10-K (Annual report)
         45                             10-K (Annual report)
         46                             10-K (Annual report)

            Filed\n(YYYY-MM-DD) Reporting for\n(YYYY-MM-DD)  \
2010_ALL 0           2010-03-01                  2010-01-01
         1           2010-02-22                  2009-12-31
2011_ALL 0           2011-03-01                  2010-12-31
         1           2011-03-01                  2010-12-31
         2           2011-05-20                  2011-03-31
...                         ...                         ...
2020_ALL 41          2020-02-20                  2019-12-31
         42          2020-04-29                  2020-02-29
         44          2020-03-25                  2019-12-31
         45          2020-02-19                  2019-12-28
         46          2020-02-20                  2019-12-31

                                 Filing entity/person   SIC  \
2010_ALL 0                                TELLABS INC  3661
         1   KONINKLIJKE PHILIPS ELECTRONICS NV (PHG)  3600
2011_ALL 0                                TELLABS INC  3661
         1                                TELLABS INC  3661
         2                             AVX Corp (AVX)  3670
...                                               ...   ...
2020_ALL 41                            CTS CORP (CTS)  3672
         42                             AZZ INC (AZZ)  3640
         44           BEL FUSE INC /NJ (BELFA, BELFB)  3677
         45                        MASIMO CORP (MASI)  3845
         46              Integer Holdings Corp (ITGR)  3690

            CIK\n(full 10 digit)           Located Incorporated  \
2010_ALL 0                317771    Naperville, IL     Delaware
         1                313216     Amsterdam, P7  Netherlands
2011_ALL 0                317771    Naperville, IL     Delaware
         1                317771    Naperville, IL     Delaware
         2                859163  Fountain Inn, SC     Delaware
...                          ...               ...          ...
2020_ALL 41                26058         Lisle, IL      Indiana
         42                 8947    Fort Worth, TX        Texas
         44               729580   Jersey City, NJ   New Jersey
         45               937556        Irvine, CA     Delaware
         46              1114483         Plano, TX     Delaware

                                           Conflict mineral(s) *adverse*  \
2010_ALL 0   Supply Chain\n\nExpect excellence\n\nthroughou...  00:00:00
         1   \t \t‘Conflict’ minerals: issues further down ...  00:00:00
2011_ALL 0   Work with supply chain to responsibly manage m...         0
         1   Conflict Minerals — Minerals such as gold, tin...         0
         2   Changes in regulatory and environmental compli...         1
...                                                        ...       ...
2020_ALL 41  Regulations related to conflict minerals could...         1
         42  New regulations related to conflict minerals c...         1
         44  Regulations related to conflict minerals will ...         1
         45  Conflict Minerals and Supply Chain. We are sub...         1
         46  Conflict Minerals and Supply Chain. We are sub...         0

             *expense*,*cost*  *reputation*  *difficult*  *support*  \
2010_ALL 0                  0             0            0          0
         1                  0             0            0          0
2011_ALL 0                  0             0            0          0
         1                  0             0            0          0
         2                  1             0            1          0
...                       ...           ...          ...        ...
2020_ALL 41                 1             1            0          0
         42                 1             1            0          0
         44                 1             1            0          0
         45                 1             0            1          0
         46                 0             0            0          0

                        *commit*  *effort*  *compliance*, *comply*
2010_ALL 0   1900-01-01 00:00:00  00:00:00                     0.0
         1              00:00:00  00:00:00                     0.0
2011_ALL 0                     1         0                     1.0
         1                     0         0                     0.0
         2                     0         0                     1.0
...                          ...       ...                     ...
2020_ALL 41                    0       0.0                     1.0
         42                    0       1.0                     1.0
         44                    0       1.0                     1.0
         45                    0       0.0                     1.0
         46                    0       1.0                     1.0

[2994 rows x 17 columns]

In [8]:
dataframe['Filed\n(YYYY-MM-DD)']

2010_ALL  0    2010-03-01
          1    2010-02-22
2011_ALL  0    2011-03-01
          1    2011-03-01
          2    2011-05-20
                  ...
2020_ALL  41   2020-02-20
          42   2020-04-29
          44   2020-03-25
          45   2020-02-19
          46   2020-02-20
Name: Filed\n(YYYY-MM-DD), Length: 2994, dtype: datetime64[ns]

In [9]:
dataframe_2010 = dataframe[dataframe['Filed\n(YYYY-MM-DD)'].dt.year == 2010]

In [10]:
dataframe_2010

                                                Form & File  \
2010_ALL 0                       10-K (Annual report) EX-13
         1  20-F (Annual report - foreign issuer) EX-15.(B)

           Filed\n(YYYY-MM-DD) Reporting for\n(YYYY-MM-DD)  \
2010_ALL 0          2010-03-01                  2010-01-01
         1          2010-02-22                  2009-12-31

                                Filing entity/person   SIC  \
2010_ALL 0                               TELLABS INC  3661
         1  KONINKLIJKE PHILIPS ELECTRONICS NV (PHG)  3600

           CIK\n(full 10 digit)         Located Incorporated  \
2010_ALL 0               317771  Naperville, IL     Delaware
         1               313216   Amsterdam, P7  Netherlands

                                          Conflict mineral(s) *adverse*  \
2010_ALL 0  Supply Chain\n\nExpect excellence\n\nthroughou...  00:00:00
         1  \t \t‘Conflict’ minerals: issues further down ...  00:00:00

            *expense*,*cost*  *reputation*  *difficult*  *support*  \
2010_ALL 0                 0             0            0          0
         1                 0             0            0          0

                       *commit*  *effort*  *compliance*, *comply*
2010_ALL 0  1900-01-01 00:00:00  00:00:00                     0.0
         1             00:00:00  00:00:00                     0.0